import { Solar } from 'lunar-javascript'
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'

const format=process.argv[2]||'hoy'
const date=process.argv[3]||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City'}).format(new Date())
const outDir='public/social/generated'
const CTA='Descubre tu carta completa en MI MAPA. Toda la información y la app son gratis.'
const palettes={water:['#355d71','#6f91a2','#d5e4e8'],wood:['#3f5841','#71845d','#dce7d4'],fire:['#8f422d','#d4774c','#f6d9c9'],earth:['#735535','#b58b55','#ebddc5'],metal:['#555b5e','#8b8d8a','#e4e4e1']}
const animalOrder=['rat','ox','tiger','rabbit','dragon','snake','horse','goat','monkey','rooster','dog','pig']
const animals={rat:['Rata','子','water',1960],ox:['Buey','丑','earth',1961],tiger:['Tigre','寅','wood',1962],rabbit:['Conejo','卯','wood',1963],dragon:['Dragón','辰','earth',1964],snake:['Víbora','巳','fire',1965],horse:['Caballo','午','fire',1966],goat:['Cabra','未','earth',1967],monkey:['Mono','申','metal',1968],rooster:['Gallo','酉','metal',1969],dog:['Perro','戌','earth',1970],pig:['Cerdo','亥','water',1971]}
const centerOrder=['jia','yi','bing','ding','wu','ji','geng','xin','ren','gui']
const centers={
  jia:['Madera Yang','甲','wood','¿Eres de quien empieza antes de tener todo resuelto?','Cuando ves una posibilidad, te dan ganas de moverla y sostenerla hasta que avance.'],
  yi:['Madera Yin','乙','wood','¿Detectas rápido cómo ajustar algo para que funcione?','Encuentras rutas alternas y sabes adaptarte mientras conservas lo que te importa.'],
  bing:['Fuego Yang','丙','fire','¿Cuando algo te emociona se te nota en toda la cara?','Enciendes ideas y haces que otras personas quieran mirar hacia ahí.'],
  ding:['Fuego Yin','丁','fire','¿Te prende más una conversación buena que hacer ruido?','Prefieres profundizar, preparar y cuidar detalles antes de mostrarte por completo.'],
  wu:['Tierra Yang','戊','earth','¿Terminas siendo quien sostiene el plan?','Buscas que las cosas aterricen y que la gente tenga dónde apoyarse.'],
  ji:['Tierra Yin','己','earth','¿Piensas primero en qué necesita cada quien?','Detectas los cuidados pequeños que mantienen un proceso funcionando.'],
  geng:['Metal Yang','庚','metal','¿Ves el problema y ya quieres resolverlo?','Cortas lo que estorba y actúas cuando el momento pide decisión.'],
  xin:['Metal Yin','辛','metal','¿Te cuesta ignorar algo que podría quedar mucho mejor?','Afinas, ordenas y elevas el estándar de lo que pasa por tus manos.'],
  ren:['Agua Yang','壬','water','¿Antes de hablar ya conectaste varias piezas?','Juntas información y encuentras salidas que otras personas todavía pasan por alto.'],
  gui:['Agua Yin','癸','water','¿Guardas detalles que luego resultan claves?','Lees el ambiente y captas señales pequeñas antes de que todo se haga evidente.'],
}
const animalCopy={
  rat:['¿Siempre ubicas por dónde conviene entrar?','La Rata observa, calcula y encuentra recursos donde otras personas ven poco.'],ox:['¿Te desespera que cambien el plan a media ruta?','El Buey avanza a su ritmo, cumple y prefiere que las cosas tengan base.'],tiger:['¿Te animas más cuando algo parece difícil?','El Tigre entra con fuerza, protege lo suyo y disfruta un reto que vale la pena.'],rabbit:['¿Lees el ambiente antes de decir algo?','El Conejo cuida el tono, el espacio y las relaciones antes de moverse.'],dragon:['¿Llegas a una reunión y de pronto todo se mueve?','El Dragón junta presencia, ambición y ganas de construir algo que se note.'],snake:['¿Prefieres entender bien antes de mostrar tus cartas?','La Víbora observa de cerca, elige su momento y detecta lo que falta.'],horse:['¿Te pesa sentir que estás estancado?','El Caballo necesita movimiento, experiencias y una ruta propia.'],goat:['¿Te importa que un lugar se sienta bien para todos?','La Cabra aporta sensibilidad, gusto y una forma de cuidar que une al grupo.'],monkey:['¿Ante un problema ya pensaste tres formas de resolverlo?','El Mono aprende rápido, prueba y disfruta encontrar una salida ingeniosa.'],rooster:['¿Ves rápido qué sobra y qué falta?','El Gallo ordena, afina y dice lo necesario cuando algo necesita claridad.'],dog:['¿Te tomas muy en serio a tu gente?','El Perro valora la lealtad, detecta incoherencias y defiende lo que considera justo.'],pig:['¿La gente termina contándote cosas apenas te conoce?','El Cerdo crea confianza, disfruta lo bueno y abre espacio para los demás.']}
const clashes={rat:'horse',ox:'goat',tiger:'monkey',rabbit:'rooster',dragon:'dog',snake:'pig',horse:'rat',goat:'ox',monkey:'tiger',rooster:'rabbit',dog:'dragon',pig:'snake'}

const [year,month,day]=date.split('-').map(Number)
const eight=Solar.fromYmdHms(year,month,day,12,0,0).getLunar().getEightChar()
const hanAnimal=Object.fromEntries(Object.entries(animals).map(([key,value])=>[value[1],key]))
const dayAnimal=hanAnimal[eight.getDayZhi()],monthAnimal=hanAnimal[eight.getMonthZhi()]
const rhythms=[['Arrancar','empezar eso que llevas posponiendo','convertir una intención clara en movimiento'],['Depurar','quitarte pendientes de encima','quitar peso y dejar espacio para lo que sigue'],['Consolidar','dejar algo bien amarrado','dar estructura a lo que ya empezaste'],['Reunir','juntar personas, ideas o recursos','acercar las piezas que necesitas'],['Abrir','probar una ruta nueva','hacer espacio para una posibilidad'],['Equilibrar','ordenar antes de decidir','ver las dos partes de una situación'],['Cerrar','ponerle punto final a algo','terminar con claridad'],['Recibir','escuchar y dejar que algo llegue','observar antes de mover piezas'],['Desmontar','ver qué ya perdió sentido','editar, recortar y simplificar'],['Riesgo','actuar con un poco más de valentía','dar un paso que abre movimiento'],['Establecer','poner reglas claras','definir límites y acuerdos'],['Peligro','dejar espacio y medir mejor el paso','revisar antes de comprometerte']]
const rhythm=rhythms[(animalOrder.indexOf(dayAnimal)-animalOrder.indexOf(monthAnimal)+12)%12]
const week=Math.floor((Date.UTC(year,month-1,day)-Date.UTC(2026,0,1))/604800000)

function yearsFor(base){const out=[];for(let y=base-12;y<=2031;y+=12)out.push(y);return out}
function esc(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]))}
function lines(value,max){const words=String(value).split(/\s+/),out=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(line&&next.length>max){out.push(line);line=word}else line=next}if(line)out.push(line);return out}
function tspans(value,x,y,lineHeight,max){return lines(value,max).map((line,index)=>`<tspan x="${x}" y="${y+index*lineHeight}">${esc(line)}</tspan>`).join('')}
function card(post,index){
  const colors=palettes[post.palette],contours=Array.from({length:8},(_,i)=>`<path d="M-40 ${245+i*126} C190 ${175+i*126} 300 ${335+i*126} 520 ${250+i*126} S860 ${165+i*126} 1130 ${278+i*126}"/>`).join('')
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><defs><linearGradient id="paper" x2="1" y2="1"><stop stop-color="#f7f1e7"/><stop offset="1" stop-color="#e8dccb"/></linearGradient></defs><rect width="1080" height="1350" fill="url(#paper)"/><g fill="none" stroke="#4d4031" stroke-opacity=".14" stroke-width="2">${contours}</g><path d="M122 1110 C255 950 220 850 410 740 S610 430 930 286" fill="none" stroke="${colors[1]}" stroke-width="6" stroke-dasharray="18 16"/><rect x="48" y="48" width="984" height="1254" rx="58" fill="#fffdf7" fill-opacity=".88" stroke="#4d4031" stroke-opacity=".16" stroke-width="2"/><text x="88" y="108" fill="${colors[0]}" font-family="Arial" font-size="24" font-weight="800">十  MI MAPA</text><text x="992" y="106" text-anchor="end" fill="${colors[0]}" font-family="Arial" font-size="16" font-weight="700">${esc(post.eyebrow)}</text><text x="88" y="202" fill="${colors[0]}" font-family="Arial" font-size="18" font-weight="800">${esc(post.title)}</text><circle cx="844" cy="360" r="154" fill="${colors[2]}"/><circle cx="844" cy="360" r="124" fill="none" stroke="${colors[1]}" stroke-width="4"/><text x="844" y="378" text-anchor="middle" fill="${colors[0]}" font-family="Georgia" font-size="48" font-weight="700">${esc(post.detail)}</text><text fill="#3e3832" font-family="Georgia" font-size="62" font-weight="700">${tspans(post.hook,88,360,70,24)}</text><rect x="88" y="820" width="840" height="238" rx="32" fill="#fffdf7" fill-opacity=".78" stroke="#4d4031" stroke-opacity=".12"/><text x="128" y="875" fill="${colors[0]}" font-family="Arial" font-size="15" font-weight="800">ASÍ SE NOTA</text><text fill="#3e3832" font-family="Georgia" font-size="29">${tspans(post.body,128,930,38,45)}</text><text x="88" y="1205" fill="${colors[0]}" font-family="Arial" font-size="18" font-weight="800">TU CARTA COMPLETA ES GRATIS</text><text x="88" y="1243" fill="#3e3832" font-family="Arial" font-size="16">ebermed.github.io/mi-mapa</text><text x="992" y="1238" text-anchor="end" fill="${colors[0]}" font-family="Arial" font-size="24" font-weight="700">↗</text></svg>`
}

function todayPost(){const animal=animals[dayAnimal],label=new Intl.DateTimeFormat('es-MX',{weekday:'long',day:'numeric',month:'long'}).format(new Date(Date.UTC(year,month-1,day))).toUpperCase(),hook=`Hoy se presta para ${rhythm[1]}.`,body=`El calendario marca hoy como día de ${animal[0]}. Tu carta muestra cómo ese ritmo se cruza contigo.`;return{title:`HOY · ${rhythm[0].toUpperCase()}`,eyebrow:label,hook,body,detail:animal[0],palette:animal[2],caption:`${hook}\n\nEste ritmo colectivo ayuda a ${rhythm[2]}.\n\n${body}\n\n${CTA}`}}
function centerPost(){const key=centerOrder[((week%centerOrder.length)+centerOrder.length)%centerOrder.length],item=centers[key];return{title:`TU CENTRO: ${item[0].toUpperCase()}`,eyebrow:'LOS 10 CENTROS',hook:item[3],body:item[4],detail:item[1],palette:item[2],caption:`${item[3]}\n\n${item[4]}\n\nEn MI MAPA le llamamos tu centro: la forma en que vuelves a ti para decidir.\n\n${CTA}`}}
function animalPost(){const key=animalOrder[((week%animalOrder.length)+animalOrder.length)%animalOrder.length],meta=animals[key],copy=animalCopy[key],years=yearsFor(meta[3]);return{title:`SI ERES ${meta[0].toUpperCase()}`,eyebrow:'LOS 12 ANIMALES',hook:copy[0],body:`${copy[1]} Años: ${years.join(' · ')}.`,detail:meta[1],palette:meta[2],caption:`${copy[0]}\n\n${copy[1]}\n\nAños: ${years.join(', ')}. Quienes nacieron entre enero y los primeros días de febrero pueden cambiar de animal según su fecha exacta.\n\n${CTA}`}}
function weekPosts(part){return animalOrder.slice(part?6:0,part?12:6).map(key=>{const meta=animals[key],years=yearsFor(meta[3]),focus=key===dayAnimal?'El ritmo de la semana te queda cerca: úsalo en una prioridad concreta.':clashes[key]===dayAnimal?'Esta semana pide margen antes de responder o cerrar algo.':'La semana se presta para elegir una prioridad y moverla paso a paso.';return{title:`SEMANA PARA ${meta[0].toUpperCase()}`,eyebrow:'ESTA SEMANA',hook:focus,body:`Años: ${years.join(' · ')}.`,detail:meta[1],palette:meta[2]}})}

let posts,caption
if(format==='hoy'){posts=[todayPost()];caption=posts[0].caption}else if(format==='centro'){posts=[centerPost()];caption=posts[0].caption}else if(format==='animal'){posts=[animalPost()];caption=posts[0].caption}else if(format==='semana-a'||format==='semana-b'){posts=weekPosts(format==='semana-b'?1:0);caption=`Esta semana, cada animal encuentra un ritmo distinto. Busca el tuyo por año de nacimiento y descubre el resto de tu carta gratis en MI MAPA.\n\n${CTA}`}else throw new Error(`Formato desconocido: ${format}`)

rmSync(outDir,{recursive:true,force:true});mkdirSync(outDir,{recursive:true})
const items=posts.map((post,index)=>{const name=`${format}-${date}-${index+1}.svg`;writeFileSync(`${outDir}/${name}`,card(post,index));return name.replace('.svg','.jpg')})
writeFileSync(`${outDir}/post.json`,JSON.stringify({format,date,caption,items},null,2))
console.log(JSON.stringify({format,date,items}))
