import { Solar } from 'lunar-javascript'
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'

const format=process.argv[2]||'hoy'
const date=process.argv[3]||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City'}).format(new Date())
const outDir='public/social/generated'
const CTA='Descubre tu carta completa en MI MAPA. Toda la información y la app son gratis.'
const palettes={water:['#355d71','#6f91a2','#d5e4e8'],wood:['#3f5841','#71845d','#dce7d4'],fire:['#8f422d','#d4774c','#f6d9c9'],earth:['#735535','#b58b55','#ebddc5'],metal:['#555b5e','#8b8d8a','#e4e4e1']}
const animalOrder=['rat','ox','tiger','rabbit','dragon','snake','horse','goat','monkey','rooster','dog','pig']
const animals={rat:['Rata','子','water',1960],ox:['Buey','丑','earth',1961],tiger:['Tigre','寅','wood',1962],rabbit:['Conejo','卯','wood',1963],dragon:['Dragón','辰','earth',1964],snake:['Víbora','巳','fire',1965],horse:['Caballo','午','fire',1966],goat:['Cabra','未','earth',1967],monkey:['Mono','申','metal',1968],rooster:['Gallo','酉','metal',1969],dog:['Perro','戌','earth',1970],pig:['Cerdo','亥','water',1971]}
const centerOrder=['jia','yi','bing','ding','wu','ji','geng','xin','ren','gui']
const centers={
  jia:['Madera Yang','甲','wood','¿Empiezas antes de tener todo resuelto?','Cuando ves una posibilidad, te dan ganas de moverla y sostenerla hasta que avance.'],
  yi:['Madera Yin','乙','wood','¿Encuentras otra forma cuando el plan falla?','Ajustas la ruta mientras conservas lo que te importa.'],
  bing:['Fuego Yang','丙','fire','¿Se te nota cuando algo te emociona?','Enciendes ideas y haces que otras personas quieran mirar hacia ahí.'],
  ding:['Fuego Yin','丁','fire','¿Prefieres entender bien antes de mostrar lo que haces?','Preparas, profundizas y cuidas detalles antes de mostrarte por completo.'],
  wu:['Tierra Yang','戊','earth','¿Terminas sosteniendo el plan de todos?','Buscas que las cosas aterricen y que la gente tenga dónde apoyarse.'],
  ji:['Tierra Yin','己','earth','¿Detectas qué necesita cada persona?','Ves los cuidados pequeños que mantienen un proceso funcionando.'],
  geng:['Metal Yang','庚','metal','¿Ves el problema y quieres resolverlo ya?','Cortas lo que estorba y actúas cuando el momento pide decisión.'],
  xin:['Metal Yin','辛','metal','¿Notas enseguida lo que podría quedar mejor?','Afinas, ordenas y elevas el estándar de lo que pasa por tus manos.'],
  ren:['Agua Yang','壬','water','¿Piensas en varias salidas al mismo tiempo?','Conectas información y encuentras rutas que otras personas pasan por alto.'],
  gui:['Agua Yin','癸','water','¿Guardas detalles que después resultan clave?','Lees el ambiente y captas señales pequeñas antes de que todo sea evidente.'],
}
const animalCopy={
  rat:['¿Siempre encuentras por dónde entrar?','La Rata observa, calcula y encuentra recursos donde otras personas ven poco.'],ox:['¿Te pesa que cambien el plan a media ruta?','El Buey avanza a su ritmo, cumple y prefiere que las cosas tengan base.'],tiger:['¿Te activas cuando algo parece difícil?','El Tigre entra con fuerza, protege lo suyo y disfruta un reto que vale la pena.'],rabbit:['¿Lees el ambiente antes de hablar?','El Conejo cuida el tono, el espacio y las relaciones antes de moverse.'],dragon:['¿Llegas y terminas moviendo todo?','El Dragón junta presencia, ambición y ganas de construir algo que se note.'],snake:['¿Prefieres entender antes de mostrar tus cartas?','La Víbora observa de cerca, elige su momento y detecta lo que falta.'],horse:['¿Te pesa sentirte estancado?','El Caballo necesita movimiento, experiencias y una ruta propia.'],goat:['¿Notas cuando un lugar se siente raro?','La Cabra aporta sensibilidad, gusto y una forma de cuidar que une al grupo.'],monkey:['¿Ante un problema ya imaginaste tres soluciones?','El Mono aprende rápido, prueba y disfruta encontrar una salida ingeniosa.'],rooster:['¿Ves rápido qué sobra y qué falta?','El Gallo ordena, afina y dice lo necesario cuando algo necesita claridad.'],dog:['¿Te tomas muy en serio a tu gente?','El Perro valora la lealtad, detecta incoherencias y defiende lo que considera justo.'],pig:['¿La gente termina contándote todo?','El Cerdo crea confianza, disfruta lo bueno y abre espacio para los demás.']}
const clashes={rat:'horse',ox:'goat',tiger:'monkey',rabbit:'rooster',dragon:'dog',snake:'pig',horse:'rat',goat:'ox',monkey:'tiger',rooster:'rabbit',dog:'dragon',pig:'snake'}

const [year,month,day]=date.split('-').map(Number)
const eight=Solar.fromYmdHms(year,month,day,12,0,0).getLunar().getEightChar()
const hanAnimal=Object.fromEntries(Object.entries(animals).map(([key,value])=>[value[1],key]))
const dayAnimal=hanAnimal[eight.getDayZhi()],monthAnimal=hanAnimal[eight.getMonthZhi()]
const rhythms=[['Arrancar','empezar eso que llevas posponiendo','convertir una intención clara en movimiento'],['Depurar','quitarte pendientes de encima','quitar peso y dejar espacio para lo que sigue'],['Consolidar','dejar algo bien amarrado','dar estructura a lo que ya empezaste'],['Reunir','juntar personas, ideas o recursos','acercar las piezas que necesitas'],['Abrir','probar una ruta nueva','hacer espacio para una posibilidad'],['Equilibrar','ordenar antes de decidir','ver las dos partes de una situación'],['Cerrar','ponerle punto final a algo','terminar con claridad'],['Recibir','escuchar y dejar que algo llegue','observar antes de mover piezas'],['Desmontar','ver qué ya perdió sentido','editar, recortar y simplificar'],['Riesgo','actuar con un poco más de valentía','dar un paso que abre movimiento'],['Establecer','poner reglas claras','definir límites y acuerdos'],['Peligro','dejar espacio y medir mejor el paso','revisar antes de comprometerte']]
const rhythm=rhythms[(animalOrder.indexOf(dayAnimal)-animalOrder.indexOf(monthAnimal)+12)%12]
const displayHooks={Arrancar:'Tu ritmo pide movimiento.',Depurar:'Tu ritmo pide espacio.',Consolidar:'Tu ritmo pide estructura.',Reunir:'Tu ritmo pide acercar piezas.',Abrir:'Tu ritmo pide una ruta nueva.',Equilibrar:'Tu ritmo pide balance.',Cerrar:'Tu ritmo pide un punto final.',Recibir:'Tu ritmo pide escuchar.',Desmontar:'Tu ritmo pide simplificar.',Riesgo:'Tu ritmo pide valor.',Establecer:'Tu ritmo pide límites claros.',Peligro:'Tu ritmo pide medir el paso.'}
const week=Math.floor((Date.UTC(year,month-1,day)-Date.UTC(2026,0,1))/604800000)
const animalPaths={
  rat:'M6.8 9a2.2 2.2 0 1 0 4.4 0M12.8 9a2.2 2.2 0 1 0 4.4 0M8 10.5c1-2 7-2 8 0 1 2 .5 5-4 7-4.5-2-5-5-4-7zM12 13v1M6 13h3M15 13h3',ox:'M8 9C6 8 5 6 5 4c3 0 5 1 6 3M16 9c2-1 3-3 3-5-3 0-5 1-6 3M8 9c1-2 7-2 8 0v6c-1 3-7 3-8 0V9zM10 14h4',tiger:'M7 8 5 5l4 1M17 8l2-3-4 1M7 8c1-2 9-2 10 0v7c-2 3-8 3-10 0V8zM9 10h6M10 12h4M12 9v6',rabbit:'M9 9C7 6 7 2 9 2c2 0 2 4 2 7M15 9c2-3 2-7 0-7-2 0-2 4-2 7M8 10c1-2 7-2 8 0v5c-1 3-7 3-8 0v-5zM10 13h.1M14 13h.1',dragon:'M5 15c2-5 4-7 8-7 3 0 5 2 6 4-2-1-4 0-5 2-6 4-9 1zM10 8 8 5M14 8l2-3M17 11l2-1',snake:'M8 6c4-3 8-1 8 2 0 4-8 3-8 7 0 3 5 4 8 1M16 8h.1',horse:'M8 18V9l3-5 5 3v8c-1 3-5 4-8 3zM11 8h5M13 10h.1M8 11 5 9',goat:'M8 9C6 7 6 4 7 3c2 1 3 3 3 5M16 9c2-2 2-5 1-6-2 1-3 3-3 5M8 9c1-2 7-2 8 0v6c-2 3-6 3-8 0V9zM10 13h4',monkey:'M12 6a6 6 0 1 0 0 12 6 6 0 0 0 0-12M5.5 10a2 2 0 1 0 0 4M18.5 10a2 2 0 1 1 0 4M9 11c1-2 5-2 6 0v4c-1 2-5 2-6 0v-4zM10 14h4',rooster:'M9 18V8c2-3 6-3 8 0v6c-1 3-5 5-8 4zM11 6c0-2 2-3 3-1 1-2 3-1 3 1M17 9l3 2-3 1M7 10 4 8M7 13 4 14',dog:'M8 8 5 5v6M16 8l3-3v6M8 8c1-2 7-2 8 0v7c-1 3-7 3-8 0V8zM10 12h.1M14 12h.1M10 15h4',pig:'M7 9C8 6 16 6 17 9v6c-2 3-8 3-10 0V9zM8 8 6 5l4 2M16 8l2-3-4 2M9 13c1-2 5-2 6 0v2c-1 2-5 2-6 0v-2zM11 14h.1M13 14h.1'
}

function yearsFor(base){const out=[];for(let y=base-12;y<=2031;y+=12)out.push(y);return out}
function esc(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]))}
function lines(value,max){const words=String(value).split(/\s+/),out=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(line&&next.length>max){out.push(line);line=word}else line=next}if(line)out.push(line);return out}
function tspans(value,x,y,lineHeight,max){return lines(value,max).map((line,index)=>`<tspan x="${x}" y="${y+index*lineHeight}">${esc(line)}</tspan>`).join('')}
function animalIcon(key,x,y,size,color){const scale=size/24;return `<path d="${animalPaths[key]}" transform="translate(${x-size/2} ${y-size/2}) scale(${scale})" fill="none" stroke="${color}" stroke-width="${5/scale}" stroke-linecap="round" stroke-linejoin="round"/>`}
function base(post,series){const colors=palettes[post.palette],contours=Array.from({length:10},(_,i)=>`<path d="M-40 ${185+i*112} C190 ${125+i*112} 340 ${260+i*112} 560 ${190+i*112} S880 ${130+i*112} 1130 ${230+i*112}"/>`).join('');return `<defs><linearGradient id="paper" x2="1" y2="1"><stop stop-color="#faf5ea"/><stop offset=".56" stop-color="#f1e7d8"/><stop offset="1" stop-color="#e8dccb"/></linearGradient><radialGradient id="wash"><stop stop-color="${colors[2]}"/><stop offset="1" stop-color="${colors[2]}" stop-opacity="0"/></radialGradient></defs><rect width="1080" height="1350" fill="url(#paper)"/><circle cx="80" cy="700" r="370" fill="url(#wash)" opacity=".72"/><g fill="none" stroke="#413930" stroke-opacity=".12" stroke-width="2">${contours}</g><rect x="34" y="34" width="1012" height="1282" rx="52" fill="none" stroke="#413930" stroke-opacity=".14" stroke-width="2"/><text x="72" y="88" fill="${colors[0]}" font-family="Arial" font-size="20" font-weight="800">+  MI MAPA</text><text x="1008" y="86" text-anchor="end" fill="${colors[0]}" font-family="Arial" font-size="14" font-weight="800">${esc(series)}</text>`}
function footer(post){const colors=palettes[post.palette];return `<path d="M72 1236H1008" stroke="#413930" stroke-opacity=".16"/><text x="72" y="1275" fill="${colors[0]}" font-family="Arial" font-size="18" font-weight="800">TU CARTA COMPLETA ES GRATIS</text><text x="1008" y="1275" text-anchor="end" fill="#34322e" font-family="Arial" font-size="15" font-weight="600">ebermed.github.io/mi-mapa  ↗</text>`}
function todayCard(post){const c=palettes[post.palette];return `${base(post,post.eyebrow)}<text x="62" y="302" fill="${c[1]}" font-family="Arial" font-size="220" font-weight="800">HOY</text><path d="M118 650 C210 650 220 730 300 730 S420 590 510 590 S660 720 760 720 S920 610 1010 610" fill="none" stroke="${c[1]}" stroke-width="5" stroke-dasharray="14 14"/>${animalIcon(post.animalKey,610,665,500,c[1])}<path d="M150 620a18 18 0 1 0 0 36l-12 10 12 24 12-24-12-10" fill="${c[0]}"/><text fill="#313743" font-family="Georgia" font-style="italic" font-size="47" font-weight="600">${tspans(post.displayHook,72,1120,58,37)}</text>${footer(post)}`}
function centerCard(post){const c=palettes[post.palette],name=post.title.replace(/^TU CENTRO:\s*/,'');return `${base(post,'LOS 10 CENTROS')}<path d="M70 530 C180 530 190 450 310 450 S440 575 560 575 S700 380 820 380 S930 470 1020 470" fill="none" stroke="${c[1]}" stroke-width="5" stroke-dasharray="14 14"/><text x="72" y="202" fill="${c[0]}" font-family="Arial" font-size="28" font-weight="800">TU CENTRO:</text><text x="72" y="328" fill="${c[0]}" font-family="Georgia" font-size="88" font-weight="800">${esc(name)}</text><circle cx="875" cy="278" r="126" fill="${c[2]}"/><circle cx="875" cy="278" r="94" fill="none" stroke="${c[0]}" stroke-width="3"/><text x="875" y="295" text-anchor="middle" fill="${c[0]}" font-family="Georgia" font-size="46" font-weight="700">${esc(post.detail)}</text><text fill="#37342f" font-family="Georgia" font-size="68" font-weight="700">${tspans(post.hook,72,700,78,25)}</text><rect x="72" y="955" width="780" height="150" rx="28" fill="#fffdf8" fill-opacity=".72"/><text fill="${c[0]}" font-family="Georgia" font-size="27">${tspans(post.body,104,1010,38,45)}</text>${footer(post)}`}
function animalCard(post){const c=palettes[post.palette],name=post.title.replace(/^SI ERES\s*/,'');return `${base(post,`SI ERES ${name}`)}<text x="64" y="238" fill="${c[0]}" font-family="Arial" font-size="112" font-weight="900">¿TE PASA</text><text x="64" y="350" fill="${c[0]}" font-family="Arial" font-size="112" font-weight="900">ESTO?</text><path d="M70 620 C180 620 180 520 270 520 S390 700 480 700 S620 540 740 540 S900 660 1010 660" fill="none" stroke="${c[1]}" stroke-width="5" stroke-dasharray="14 14"/>${animalIcon(post.animalKey,300,625,310,c[1])}<text fill="#34322e" font-family="Georgia" font-style="italic" font-size="58" font-weight="700">${tspans(post.hook,470,550,68,17)}</text><text x="72" y="905" fill="${c[0]}" font-family="Arial" font-size="18" font-weight="800">${esc(name)}</text><text fill="#34322e" font-family="Georgia" font-size="28">${tspans(post.body,72,958,38,55)}</text><text x="72" y="1110" fill="${c[0]}" font-family="Arial" font-size="15" font-weight="800">AÑOS FRECUENTES</text><text fill="#34322e" font-family="Arial" font-size="18" font-weight="600">${tspans(post.years,72,1143,28,70)}</text>${footer(post)}`}
function weekCard(post){const c=palettes[post.palette],name=post.title.replace(/^SEMANA PARA\s*/,'');return `${base(post,`SEMANA PARA ${name}`)}<text x="64" y="240" fill="${c[0]}" font-family="Arial" font-size="138" font-weight="900">ESTA</text><text x="64" y="374" fill="${c[0]}" font-family="Arial" font-size="138" font-weight="900">SEMANA</text><path d="M105 650 C230 650 250 560 370 560 S540 705 675 705 S840 565 970 565" fill="none" stroke="${c[1]}" stroke-width="5"/><g fill="#f7f1e7" stroke="${c[0]}" stroke-width="4"><circle cx="105" cy="650" r="22"/><circle cx="675" cy="705" r="22"/><circle cx="970" cy="565" r="22"/></g><circle cx="370" cy="560" r="42" fill="${c[0]}"/>${animalIcon(post.animalKey,370,560,120,'#f7f1e7')}<text x="72" y="835" fill="${c[0]}" font-family="Arial" font-size="17" font-weight="800">${esc(name)}</text><text fill="#34322e" font-family="Georgia" font-style="italic" font-size="54" font-weight="700">${tspans(post.hook,72,910,64,24)}</text><text fill="${c[0]}" font-family="Arial" font-size="16" font-weight="700">${tspans(`Años: ${post.years}`,72,1150,25,100)}</text>${footer(post)}`}
function card(post){const content=post.format==='today'?todayCard(post):post.format==='center'?centerCard(post):post.format==='animal'?animalCard(post):weekCard(post);return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350">${content}</svg>`}

function todayPost(){const animal=animals[dayAnimal],label=new Intl.DateTimeFormat('es-MX',{weekday:'long',day:'numeric',month:'long'}).format(new Date(Date.UTC(year,month-1,day))).toUpperCase(),hook=`Hoy se presta para ${rhythm[1]}.`,body=`El calendario marca hoy como día de ${animal[0]}. Tu carta muestra cómo ese ritmo se cruza contigo.`;return{format:'today',title:`HOY · ${rhythm[0].toUpperCase()}`,eyebrow:label,hook,displayHook:displayHooks[rhythm[0]],body,animalKey:dayAnimal,detail:animal[0],palette:animal[2],caption:`${hook}\n\nEste ritmo colectivo ayuda a ${rhythm[2]}.\n\n${body}\n\n${CTA}`}}
function centerPost(){const key=centerOrder[((week%centerOrder.length)+centerOrder.length)%centerOrder.length],item=centers[key];return{format:'center',title:`TU CENTRO: ${item[0].toUpperCase()}`,eyebrow:'LOS 10 CENTROS',hook:item[3],body:item[4],detail:item[1],palette:item[2],caption:`${item[3]}\n\n${item[4]}\n\nEn MI MAPA le llamamos tu centro: la forma en que vuelves a ti para decidir.\n\n${CTA}`}}
function animalPost(){const key=animalOrder[((week%animalOrder.length)+animalOrder.length)%animalOrder.length],meta=animals[key],copy=animalCopy[key],years=yearsFor(meta[3]);return{format:'animal',title:`SI ERES ${meta[0].toUpperCase()}`,eyebrow:'LOS 12 ANIMALES',hook:copy[0],body:copy[1],years:years.join(' · '),animalKey:key,detail:meta[1],palette:meta[2],caption:`${copy[0]}\n\n${copy[1]}\n\nAños: ${years.join(', ')}. Quienes nacieron entre enero y los primeros días de febrero pueden cambiar de animal según su fecha exacta.\n\n${CTA}`}}
function weekPosts(part){return animalOrder.slice(part?6:0,part?12:6).map(key=>{const meta=animals[key],years=yearsFor(meta[3]),focus=key===dayAnimal?'El ritmo de la semana te queda cerca: úsalo en una prioridad concreta.':clashes[key]===dayAnimal?'Esta semana pide margen antes de responder o cerrar algo.':'La semana se presta para elegir una prioridad y moverla paso a paso.';return{format:'week',title:`SEMANA PARA ${meta[0].toUpperCase()}`,eyebrow:'ESTA SEMANA',hook:focus,body:'',years:years.join(' · '),animalKey:key,detail:meta[1],palette:meta[2]}})}

let posts,caption
if(format==='hoy'){posts=[todayPost()];caption=posts[0].caption}else if(format==='centro'){posts=[centerPost()];caption=posts[0].caption}else if(format==='animal'){posts=[animalPost()];caption=posts[0].caption}else if(format==='semana-a'||format==='semana-b'){posts=weekPosts(format==='semana-b'?1:0);caption=`Esta semana, cada animal encuentra un ritmo distinto. Busca el tuyo por año de nacimiento y descubre el resto de tu carta gratis en MI MAPA.\n\n${CTA}`}else throw new Error(`Formato desconocido: ${format}`)

rmSync(outDir,{recursive:true,force:true});mkdirSync(outDir,{recursive:true})
const items=posts.map((post,index)=>{const name=`${format}-${date}-${index+1}.svg`;writeFileSync(`${outDir}/${name}`,card(post,index));return name.replace('.svg','.jpg')})
writeFileSync(`${outDir}/post.json`,JSON.stringify({format,date,caption,items},null,2))
console.log(JSON.stringify({format,date,items}))
