import { Solar } from 'lunar-javascript'
import { writeFileSync, mkdirSync } from 'node:fs'

const date=process.argv[2]||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City'}).format(new Date())
const [year,month,day]=date.split('-').map(Number)
const eight=Solar.fromYmdHms(year,month,day,12,0,0).getLunar().getEightChar()
const branches={子:['Rata','agua'],丑:['Buey','tierra'],寅:['Tigre','madera'],卯:['Conejo','madera'],辰:['Dragón','tierra'],巳:['Serpiente','fuego'],午:['Caballo','fuego'],未:['Cabra','tierra'],申:['Mono','metal'],酉:['Gallo','metal'],戌:['Perro','tierra'],亥:['Cerdo','agua']}
const order=Object.keys(branches),dayBranch=eight.getDayZhi(),monthBranch=eight.getMonthZhi()
const rhythms=[['Arrancar','empezar eso que llevas posponiendo','convertir una intención clara en movimiento'],['Depurar','quitarte pendientes de encima','quitar peso y dejar espacio para lo que sigue'],['Consolidar','dejar algo bien amarrado','dar estructura a lo que ya empezaste'],['Reunir','juntar personas, ideas o recursos','acercar las piezas que necesitas'],['Abrir','probar una ruta nueva','hacer espacio para una posibilidad'],['Equilibrar','ordenar antes de decidir','ver las dos partes de una situación'],['Cerrar','ponerle punto final a algo','terminar con claridad'],['Recibir','escuchar y dejar que algo llegue','observar antes de mover piezas'],['Desmontar','ver qué ya perdió sentido','editar, recortar y simplificar'],['Riesgo','actuar con un poco más de valentía','dar un paso que abre movimiento'],['Establecer','poner reglas claras','definir límites y acuerdos'],['Peligro','dejar espacio y medir mejor el paso','revisar antes de comprometerte']]]
const rhythm=rhythms[(order.indexOf(dayBranch)-order.indexOf(monthBranch)+12)%12],animal=branches[dayBranch],label=new Intl.DateTimeFormat('es-MX',{weekday:'long',day:'numeric',month:'long'}).format(new Date(Date.UTC(year,month-1,day))).toUpperCase()
const colors={agua:['#155E75','#BCE4E8'],madera:['#355E45','#D8E4C5'],fuego:['#BC4A35','#F6D3BF'],tierra:['#9A6B37','#EAD9BB'],metal:['#59636A','#D9DEE0']}[animal[1]]
const esc=s=>s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))
const hook=`Hoy se presta para ${rhythm[1]}.`
const caption=`${hook}\n\nEste ritmo colectivo ayuda a ${rhythm[2]}.\n\nEl calendario marca hoy como día de ${animal[0]}. Tu carta muestra cómo se cruza contigo.\n\nDescubre tu carta completa en MI MAPA. Toda la información y la app son gratis.`
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><rect width="1080" height="1350" fill="#F4EDE1"/><g fill="none" stroke="#786B5B" stroke-opacity=".18" stroke-width="3">${[0,1,2,3,4,5,6].map(i=>`<path d="M-40 ${270+i*120} C190 ${190+i*120} 260 ${360+i*120} 500 ${270+i*120} S850 ${180+i*120} 1130 ${290+i*120}"/>`).join('')}</g><path d="M120 1090 C250 900 340 980 510 760 S690 500 930 300" fill="none" stroke="${colors[0]}" stroke-width="7" stroke-dasharray="18 16"/><rect x="48" y="48" width="984" height="1254" rx="56" fill="#FFFDF7" fill-opacity=".82" stroke="#786B5B" stroke-opacity=".2" stroke-width="2"/><text x="88" y="110" fill="${colors[0]}" font-family="Arial" font-size="24" font-weight="800">十  MI MAPA</text><text x="88" y="185" fill="#3E3832" font-family="Arial" font-size="20" font-weight="800">${esc(label)}</text><text x="88" y="325" fill="${colors[0]}" font-family="Georgia" font-size="96" font-weight="700">HOY</text><text x="88" y="392" fill="#3E3832" font-family="Arial" font-size="22" font-weight="800">UN DÍA PARA ${rhythm[0].toUpperCase()}</text><circle cx="824" cy="470" r="146" fill="${colors[1]}"/><circle cx="824" cy="470" r="118" fill="none" stroke="${colors[0]}" stroke-width="4"/><text x="824" y="490" text-anchor="middle" fill="${colors[0]}" font-family="Georgia" font-size="42" font-weight="700">${animal[0]}</text><foreignObject x="88" y="600" width="820" height="220"><div xmlns="http://www.w3.org/1999/xhtml" style="font:700 58px Georgia;color:#3E3832;line-height:1.12">${esc(hook)}</div></foreignObject><rect x="88" y="900" width="840" height="210" rx="28" fill="${colors[1]}" fill-opacity=".52"/><text x="130" y="960" fill="${colors[0]}" font-family="Arial" font-size="18" font-weight="800">¿POR QUÉ?</text><foreignObject x="130" y="990" width="720" height="100"><div xmlns="http://www.w3.org/1999/xhtml" style="font:28px Georgia;color:#3E3832;line-height:1.25">El calendario marca hoy como día de ${animal[0]}. Tu carta muestra cómo se cruza contigo.</div></foreignObject><text x="88" y="1220" fill="#3E3832" font-family="Arial" font-size="18" font-weight="800">TU CARTA COMPLETA ES GRATIS</text><text x="88" y="1255" fill="#3E3832" font-family="Arial" font-size="16">ebermed.github.io/mi-mapa</text></svg>`
mkdirSync('public/social',{recursive:true})
writeFileSync('public/social/hoy.svg',svg)
writeFileSync('public/social/hoy-caption.txt',caption)
