import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from 'react'
import { loadDirectory, saveDirectory, type Consultant, type DirectoryData, type Referral, type ReferralStatus } from './consultants'
import { fetchAdminDirectory, loadAdminSession, saveRemoteDirectory, signInAdmin, signOutAdmin, supabaseConfigured, uploadConsultantPhoto, type AdminSession } from './supabase'

type AdminTab='resumen'|'consultantes'|'solicitudes'|'agenda'|'comisiones'
const STATUS:ReferralStatus[]=['Nueva','Contactada','Reservada','Realizada','Cancelada']
const blankConsultant=():Consultant=>({id:'',name:'',photo:'',description:'',training:[],specialties:[],modalities:['Videollamada'],city:'',languages:['Español'],durationMinutes:60,priceLabel:'',contactUrl:'',active:true,featured:false})
const blankReferral=(consultantId=''):Referral=>({id:'',consultantId,clientName:'',contact:'',requestedAt:new Date().toISOString(),sessionAt:'',status:'Nueva',price:0,commissionPaid:false,notes:''})
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-0000-4000-8000-000000000000`
const split=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean)
const money=(value:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(value)

export default function AdminCenter({onExit}:{onExit:()=>void}){
  const [data,setData]=useState<DirectoryData>(()=>loadDirectory()),[tab,setTab]=useState<AdminTab>('resumen'),[saved,setSaved]=useState(false)
  const [consultant,setConsultant]=useState<Consultant>(blankConsultant()),[referral,setReferral]=useState<Referral>(blankReferral())
  const [session,setSession]=useState<AdminSession|null>(()=>loadAdminSession()),[authError,setAuthError]=useState(''),[syncError,setSyncError]=useState(''),[loading,setLoading]=useState(supabaseConfigured&&Boolean(loadAdminSession()))
  const active=data.consultants.filter(item=>item.active).length,completed=data.referrals.filter(item=>item.status==='Realizada')
  const totalSales=completed.reduce((sum,item)=>sum+item.price,0),totalCommission=totalSales*.1,pendingCommission=completed.filter(item=>!item.commissionPaid).reduce((sum,item)=>sum+item.price*.1,0)
  const upcoming=useMemo(()=>data.referrals.filter(item=>item.sessionAt&&item.status!=='Cancelada'&&new Date(item.sessionAt).getTime()>=Date.now()).sort((a,b)=>a.sessionAt.localeCompare(b.sessionAt)),[data.referrals])
  useEffect(()=>{if(!supabaseConfigured||!session)return;setLoading(true);fetchAdminDirectory(session.access_token).then(remote=>{setData(remote);saveDirectory(remote);setSyncError('')}).catch(()=>setSyncError('La sesión requiere volver a ingresar.')).finally(()=>setLoading(false))},[session])
  const commit=(next:DirectoryData)=>{const previous=data;setData(next);saveDirectory(next);setSaved(true);setSyncError('');window.setTimeout(()=>setSaved(false),1800);if(session)saveRemoteDirectory(next,previous,session.access_token).catch(()=>{setSyncError('El cambio quedó guardado en este dispositivo y requiere sincronización.');setData(previous);saveDirectory(previous)})}
  const saveConsultant=(event:FormEvent)=>{event.preventDefault();const item={...consultant,id:consultant.id||uid()};commit({...data,consultants:consultant.id?data.consultants.map(value=>value.id===item.id?item:value):[item,...data.consultants]});setConsultant(blankConsultant())}
  const saveReferral=(event:FormEvent)=>{event.preventDefault();const item={...referral,id:referral.id||uid(),requestedAt:referral.requestedAt||new Date().toISOString()};commit({...data,referrals:referral.id?data.referrals.map(value=>value.id===item.id?item:value):[item,...data.referrals]});setReferral(blankReferral(data.consultants[0]?.id))}
  const removeConsultant=(id:string)=>{if(confirm('¿Eliminar esta consultante y conservar sus solicitudes históricas?'))commit({...data,consultants:data.consultants.filter(item=>item.id!==id)})}
  const updateReferral=(id:string,changes:Partial<Referral>)=>commit({...data,referrals:data.referrals.map(item=>item.id===id?{...item,...changes}:item)})
  const consultantName=(id:string)=>data.consultants.find(item=>item.id===id)?.name||'Consultante archivada'
  const photo=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;if(session){uploadConsultantPhoto(file,session.access_token).then(photoUrl=>setConsultant(current=>({...current,photo:photoUrl}))).catch(()=>setSyncError('La fotografía requiere otro intento.'));return}const reader=new FileReader();reader.onload=()=>setConsultant(current=>({...current,photo:String(reader.result)}));reader.readAsDataURL(file)}
  const exportCsv=()=>{const rows=[['Fecha','Consultante','Cliente','Estado','Precio','Comisión','Pagada'],...data.referrals.map(item=>[item.sessionAt,item.consultantId?consultantName(item.consultantId):'',item.clientName,item.status,String(item.price),String(item.price*.1),item.commissionPaid?'Sí':'Pendiente'])];const csv=rows.map(row=>row.map(cell=>`"${String(cell).replaceAll('"','""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download='mi-mapa-comisiones.csv';link.click();URL.revokeObjectURL(link.href)}

  if(supabaseConfigured&&!session)return <AdminLogin onExit={onExit} error={authError} onSubmit={async(email,password)=>{setAuthError('');try{setSession(await signInAdmin(email,password))}catch(error){setAuthError(error instanceof Error?error.message:'Revisa tus datos de acceso.')}}}/>
  if(loading)return <main className="adminLogin"><div><span>十</span><small>MI MAPA</small><h1>Abriendo tu centro de control…</h1></div></main>
  return <main className="adminPage">
    <aside className="adminSidebar"><button className="adminBrand" onClick={onExit}><span>十</span><b>MI MAPA</b><small>Centro de control</small></button><nav>{([['resumen','⌂','Resumen'],['consultantes','人','Consultantes'],['solicitudes','↗','Solicitudes'],['agenda','▦','Agenda'],['comisiones','$','Comisiones']] as [AdminTab,string,string][]).map(([value,icon,label])=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}><span>{icon}</span>{label}</button>)}</nav><button className="adminExit" onClick={onExit}>← Volver a Mi Mapa</button></aside>
    <section className="adminMain"><header className="adminTop"><div><small>ADMINISTRACIÓN</small><h1>{tab==='resumen'?'Resumen':tab.charAt(0).toUpperCase()+tab.slice(1)}</h1></div><div className="adminTopActions"><span className={saved?'saved visible':'saved'}>Guardado</span>{session&&<button onClick={()=>{signOutAdmin();setSession(null)}}>Cerrar sesión</button>}</div></header>{!supabaseConfigured&&<p className="adminMode">Modo de preparación local · La conexión remota activará la sincronización global.</p>}{syncError&&<p className="adminSyncError" role="alert">{syncError}</p>}
      {tab==='resumen'&&<><section className="directorySwitch"><div><small>DIRECTORIO PÚBLICO</small><h2>{data.enabled?'Consultantes visibles':'Consultantes ocultas'}</h2><p>{data.enabled?'Las personas pueden explorar perfiles y solicitar una lectura.':'Toda la sección permanece fuera de la experiencia pública.'}</p></div><button role="switch" aria-checked={data.enabled} onClick={()=>commit({...data,enabled:!data.enabled})}><i/><span>{data.enabled?'Encendido':'Apagado'}</span></button></section><div className="adminStats"><article><small>CONSULTANTES ACTIVAS</small><b>{active}</b><span>de {data.consultants.length} registradas</span></article><article><small>SOLICITUDES</small><b>{data.referrals.length}</b><span>{data.referrals.filter(item=>item.status==='Nueva').length} nuevas</span></article><article><small>SESIONES REALIZADAS</small><b>{completed.length}</b><span>{money(totalSales)} en lecturas</span></article><article><small>COMISIÓN PENDIENTE</small><b>{money(pendingCommission)}</b><span>10% por primera sesión</span></article></div><section className="adminPanel"><header><div><small>PRÓXIMAS CITAS</small><h2>Agenda</h2></div><button onClick={()=>setTab('agenda')}>Ver agenda →</button></header>{upcoming.length?<div className="upcomingList">{upcoming.slice(0,5).map(item=><article key={item.id}><time>{new Date(item.sessionAt).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})}</time><b>{item.clientName}</b><span>{consultantName(item.consultantId)}</span></article>)}</div>:<Empty title="Tu agenda está libre" copy="Las citas reservadas aparecerán aquí."/>}</section></>}
      {tab==='consultantes'&&<div className="adminSplit"><section className="adminPanel consultantList"><header><div><small>DIRECTORIO</small><h2>{data.consultants.length} perfiles</h2></div><button onClick={()=>setConsultant(blankConsultant())}>＋ Nueva</button></header>{data.consultants.length?data.consultants.map(item=><article key={item.id}>{item.photo?<img src={item.photo} alt=""/>:<span className="photoEmpty">人</span>}<div><h3>{item.name}</h3><p>{item.specialties.join(' · ')||'Especialidades pendientes'}</p><small>{item.active?'Visible':'Oculta'}{item.featured?' · Destacada':''}</small></div><button onClick={()=>setConsultant(item)}>Editar</button></article>):<Empty title="Agrega a tu primera consultante" copy="Su perfil quedará preparado mientras el directorio siga apagado."/>}</section><ConsultantForm value={consultant} setValue={setConsultant} onSubmit={saveConsultant} onPhoto={photo} onRemove={removeConsultant}/></div>}
      {tab==='solicitudes'&&<div className="adminSplit"><section className="adminPanel requestsTable"><header><div><small>PROSPECTOS</small><h2>{data.referrals.length} solicitudes</h2></div></header>{data.referrals.length?data.referrals.map(item=><article key={item.id}><div><b>{item.clientName}</b><span>{consultantName(item.consultantId)}</span><small>{item.contact}</small></div><select value={item.status} onChange={event=>updateReferral(item.id,{status:event.target.value as ReferralStatus})}>{STATUS.map(value=><option key={value}>{value}</option>)}</select><button onClick={()=>setReferral(item)}>Editar</button></article>):<Empty title="Las solicitudes llegarán aquí" copy="También puedes registrar una manualmente desde el formulario."/>}</section><ReferralForm value={referral} setValue={setReferral} consultants={data.consultants} onSubmit={saveReferral}/></div>}
      {tab==='agenda'&&<section className="adminPanel agendaPanel"><header><div><small>CALENDARIO DE SESIONES</small><h2>Próximas citas</h2></div><button onClick={()=>setTab('solicitudes')}>＋ Registrar cita</button></header>{upcoming.length?<div className="agendaList">{upcoming.map(item=><article key={item.id}><time><b>{new Date(item.sessionAt).toLocaleDateString('es-MX',{day:'2-digit'})}</b><span>{new Date(item.sessionAt).toLocaleDateString('es-MX',{month:'short'})}</span></time><div><h3>{item.clientName}</h3><p>{consultantName(item.consultantId)}</p></div><span>{new Date(item.sessionAt).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}</span><select value={item.status} onChange={event=>updateReferral(item.id,{status:event.target.value as ReferralStatus})}>{STATUS.map(value=><option key={value}>{value}</option>)}</select></article>)}</div>:<Empty title="Tu agenda está libre" copy="Asigna fecha y hora a una solicitud para verla aquí."/>}</section>}
      {tab==='comisiones'&&<section className="adminPanel commissionPanel"><header><div><small>CONTROL DE COBRO</small><h2>{money(totalCommission)} generados</h2></div><button onClick={exportCsv}>Descargar CSV</button></header><div className="commissionSummary"><span>Por cobrar <b>{money(pendingCommission)}</b></span><span>Cobrado <b>{money(totalCommission-pendingCommission)}</b></span><span>Tasa <b>10%</b></span></div>{completed.length?<div className="commissionRows">{completed.map(item=><article key={item.id}><div><b>{item.clientName}</b><span>{consultantName(item.consultantId)} · {item.sessionAt?new Date(item.sessionAt).toLocaleDateString('es-MX'):'Fecha pendiente'}</span></div><span>{money(item.price)}</span><strong>{money(item.price*.1)}</strong><label><input type="checkbox" checked={item.commissionPaid} onChange={event=>updateReferral(item.id,{commissionPaid:event.target.checked})}/>{item.commissionPaid?'Pagada':'Pendiente'}</label></article>)}</div>:<Empty title="Las comisiones aparecerán aquí" copy="Una solicitud genera comisión al marcarse como realizada."/>}</section>}
    </section>
  </main>
}

function ConsultantForm({value,setValue,onSubmit,onPhoto,onRemove}:{value:Consultant;setValue:(value:Consultant)=>void;onSubmit:(event:FormEvent)=>void;onPhoto:(event:ChangeEvent<HTMLInputElement>)=>void;onRemove:(id:string)=>void}){
  return <form className="adminPanel adminForm" onSubmit={onSubmit}><header><div><small>PERFIL</small><h2>{value.id?'Editar consultante':'Nueva consultante'}</h2></div>{value.id&&<button type="button" className="danger" onClick={()=>onRemove(value.id)}>Eliminar</button>}</header><label className="photoField">{value.photo?<img src={value.photo} alt="Vista previa"/>:<span>＋ Foto</span>}<input type="file" accept="image/*" onChange={onPhoto}/></label><label>Nombre público<input required value={value.name} onChange={event=>setValue({...value,name:event.target.value})}/></label><label>Descripción<textarea required rows={4} value={value.description} onChange={event=>setValue({...value,description:event.target.value})}/></label><label>Formación <small>Separada por comas</small><input value={value.training.join(', ')} onChange={event=>setValue({...value,training:split(event.target.value)})}/></label><label>Especialidades <small>Separadas por comas</small><input value={value.specialties.join(', ')} onChange={event=>setValue({...value,specialties:split(event.target.value)})}/></label><div className="formColumns"><label>Ciudad<input value={value.city} onChange={event=>setValue({...value,city:event.target.value})}/></label><label>Idiomas<input value={value.languages.join(', ')} onChange={event=>setValue({...value,languages:split(event.target.value)})}/></label><label>Duración<input type="number" min="15" step="5" value={value.durationMinutes} onChange={event=>setValue({...value,durationMinutes:Number(event.target.value)})}/></label><label>Precio mostrado<input placeholder="$1,200 MXN" value={value.priceLabel} onChange={event=>setValue({...value,priceLabel:event.target.value})}/></label></div><label>Enlace de contacto<input type="url" placeholder="https://wa.me/..." value={value.contactUrl} onChange={event=>setValue({...value,contactUrl:event.target.value})}/></label><fieldset><legend>Modalidad</legend>{(['Videollamada','Presencial'] as const).map(mode=><label key={mode}><input type="checkbox" checked={value.modalities.includes(mode)} onChange={event=>setValue({...value,modalities:event.target.checked?[...value.modalities,mode]:value.modalities.filter(item=>item!==mode)})}/>{mode}</label>)}</fieldset><div className="formToggles"><label><input type="checkbox" checked={value.active} onChange={event=>setValue({...value,active:event.target.checked})}/>Perfil visible</label><label><input type="checkbox" checked={value.featured} onChange={event=>setValue({...value,featured:event.target.checked})}/>Perfil destacado</label></div><button className="primary" type="submit">Guardar consultante</button></form>
}

function ReferralForm({value,setValue,consultants,onSubmit}:{value:Referral;setValue:(value:Referral)=>void;consultants:Consultant[];onSubmit:(event:FormEvent)=>void}){
  return <form className="adminPanel adminForm" onSubmit={onSubmit}><header><div><small>SOLICITUD</small><h2>{value.id?'Editar solicitud':'Registro manual'}</h2></div></header><label>Consultante<select required value={value.consultantId} onChange={event=>setValue({...value,consultantId:event.target.value})}><option value="">Selecciona</option>{consultants.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Nombre del cliente<input required value={value.clientName} onChange={event=>setValue({...value,clientName:event.target.value})}/></label><label>Teléfono o correo<input required value={value.contact} onChange={event=>setValue({...value,contact:event.target.value})}/></label><div className="formColumns"><label>Fecha de sesión<input type="datetime-local" value={value.sessionAt} onChange={event=>setValue({...value,sessionAt:event.target.value})}/></label><label>Precio acordado<input type="number" min="0" step="50" value={value.price||''} onChange={event=>setValue({...value,price:Number(event.target.value)})}/></label></div><label>Estado<select value={value.status} onChange={event=>setValue({...value,status:event.target.value as ReferralStatus})}>{STATUS.map(item=><option key={item}>{item}</option>)}</select></label><label>Notas<textarea rows={4} value={value.notes} onChange={event=>setValue({...value,notes:event.target.value})}/></label><button className="primary" type="submit">Guardar solicitud</button></form>
}

function Empty({title,copy}:{title:string;copy:string}){return <div className="adminEmpty"><span>○</span><h3>{title}</h3><p>{copy}</p></div>}

function AdminLogin({onExit,onSubmit,error}:{onExit:()=>void;onSubmit:(email:string,password:string)=>Promise<void>;error:string}){
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false)
  return <main className="adminLogin"><button onClick={onExit}>← Volver</button><form onSubmit={async event=>{event.preventDefault();setBusy(true);await onSubmit(email,password);setBusy(false)}}><span>十</span><small>MI MAPA · ADMINISTRACIÓN</small><h1>Centro de control</h1><p>Ingresa con la cuenta administradora para gestionar consultantes, citas y comisiones.</p><label>Correo<input type="email" autoComplete="email" required value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Contraseña<input type="password" autoComplete="current-password" required value={password} onChange={event=>setPassword(event.target.value)}/></label>{error&&<p className="adminLoginError" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Ingresando…':'Entrar'}</button></form></main>
}
