export type BirthLocation = { city:string; country:string; timezone:string; longitude:number }

export const locations:BirthLocation[] = [
  {city:'Ciudad de México',country:'México',timezone:'America/Mexico_City',longitude:-99.13},
  {city:'Guadalajara',country:'México',timezone:'America/Mexico_City',longitude:-103.35},
  {city:'Monterrey',country:'México',timezone:'America/Monterrey',longitude:-100.31},
  {city:'Puebla',country:'México',timezone:'America/Mexico_City',longitude:-98.21},
  {city:'León',country:'México',timezone:'America/Mexico_City',longitude:-101.68},
  {city:'Querétaro',country:'México',timezone:'America/Mexico_City',longitude:-100.39},
  {city:'Toluca',country:'México',timezone:'America/Mexico_City',longitude:-99.66},
  {city:'Mérida',country:'México',timezone:'America/Merida',longitude:-89.62},
  {city:'Cancún',country:'México',timezone:'America/Cancun',longitude:-86.85},
  {city:'Tijuana',country:'México',timezone:'America/Tijuana',longitude:-117.04},
  {city:'Ciudad Juárez',country:'México',timezone:'America/Ciudad_Juarez',longitude:-106.49},
  {city:'Chihuahua',country:'México',timezone:'America/Chihuahua',longitude:-106.07},
  {city:'Hermosillo',country:'México',timezone:'America/Hermosillo',longitude:-110.96},
  {city:'Culiacán',country:'México',timezone:'America/Mazatlan',longitude:-107.39},
  {city:'Mazatlán',country:'México',timezone:'America/Mazatlan',longitude:-106.41},
  {city:'Aguascalientes',country:'México',timezone:'America/Mexico_City',longitude:-102.29},
  {city:'San Luis Potosí',country:'México',timezone:'America/Mexico_City',longitude:-100.98},
  {city:'Morelia',country:'México',timezone:'America/Mexico_City',longitude:-101.19},
  {city:'Veracruz',country:'México',timezone:'America/Mexico_City',longitude:-96.13},
  {city:'Oaxaca',country:'México',timezone:'America/Mexico_City',longitude:-96.73},
  {city:'Tuxtla Gutiérrez',country:'México',timezone:'America/Mexico_City',longitude:-93.11},
  {city:'Villahermosa',country:'México',timezone:'America/Mexico_City',longitude:-92.93},
  {city:'Saltillo',country:'México',timezone:'America/Monterrey',longitude:-101.00},
  {city:'Torreón',country:'México',timezone:'America/Monterrey',longitude:-103.41},
  {city:'La Paz',country:'México',timezone:'America/Mazatlan',longitude:-110.31},
  {city:'Mexicali',country:'México',timezone:'America/Tijuana',longitude:-115.47},
  {city:'Acapulco',country:'México',timezone:'America/Mexico_City',longitude:-99.87},
  {city:'Campeche',country:'México',timezone:'America/Merida',longitude:-90.53},
  {city:'Celaya',country:'México',timezone:'America/Mexico_City',longitude:-100.82},
  {city:'Chetumal',country:'México',timezone:'America/Cancun',longitude:-88.30},
  {city:'Chilpancingo',country:'México',timezone:'America/Mexico_City',longitude:-99.50},
  {city:'Coatzacoalcos',country:'México',timezone:'America/Mexico_City',longitude:-94.45},
  {city:'Colima',country:'México',timezone:'America/Mexico_City',longitude:-103.72},
  {city:'Cuernavaca',country:'México',timezone:'America/Mexico_City',longitude:-99.22},
  {city:'Durango',country:'México',timezone:'America/Monterrey',longitude:-104.67},
  {city:'Ensenada',country:'México',timezone:'America/Tijuana',longitude:-116.60},
  {city:'Guanajuato',country:'México',timezone:'America/Mexico_City',longitude:-101.26},
  {city:'Irapuato',country:'México',timezone:'America/Mexico_City',longitude:-101.35},
  {city:'Jalapa',country:'México',timezone:'America/Mexico_City',longitude:-96.92},
  {city:'Los Mochis',country:'México',timezone:'America/Mazatlan',longitude:-108.99},
  {city:'Manzanillo',country:'México',timezone:'America/Mexico_City',longitude:-104.34},
  {city:'Matamoros',country:'México',timezone:'America/Matamoros',longitude:-97.50},
  {city:'Nuevo Laredo',country:'México',timezone:'America/Matamoros',longitude:-99.51},
  {city:'Pachuca',country:'México',timezone:'America/Mexico_City',longitude:-98.74},
  {city:'Puerto Vallarta',country:'México',timezone:'America/Mexico_City',longitude:-105.23},
  {city:'Reynosa',country:'México',timezone:'America/Matamoros',longitude:-98.29},
  {city:'Tampico',country:'México',timezone:'America/Mexico_City',longitude:-97.86},
  {city:'Tepic',country:'México',timezone:'America/Mazatlan',longitude:-104.89},
  {city:'Zacatecas',country:'México',timezone:'America/Mexico_City',longitude:-102.58},
  {city:'Playa del Carmen',country:'México',timezone:'America/Cancun',longitude:-87.07},
  {city:'San Cristóbal de las Casas',country:'México',timezone:'America/Mexico_City',longitude:-92.64},
  {city:'Guatemala',country:'Guatemala',timezone:'America/Guatemala',longitude:-90.51},
  {city:'San Salvador',country:'El Salvador',timezone:'America/El_Salvador',longitude:-89.19},
  {city:'Tegucigalpa',country:'Honduras',timezone:'America/Tegucigalpa',longitude:-87.19},
  {city:'Managua',country:'Nicaragua',timezone:'America/Managua',longitude:-86.25},
  {city:'San José',country:'Costa Rica',timezone:'America/Costa_Rica',longitude:-84.09},
  {city:'Ciudad de Panamá',country:'Panamá',timezone:'America/Panama',longitude:-79.52},
  {city:'La Habana',country:'Cuba',timezone:'America/Havana',longitude:-82.38},
  {city:'Santo Domingo',country:'Rep. Dominicana',timezone:'America/Santo_Domingo',longitude:-69.93},
  {city:'Bogotá',country:'Colombia',timezone:'America/Bogota',longitude:-74.07},
  {city:'Medellín',country:'Colombia',timezone:'America/Bogota',longitude:-75.56},
  {city:'Cali',country:'Colombia',timezone:'America/Bogota',longitude:-76.52},
  {city:'Caracas',country:'Venezuela',timezone:'America/Caracas',longitude:-66.90},
  {city:'Quito',country:'Ecuador',timezone:'America/Guayaquil',longitude:-78.47},
  {city:'Guayaquil',country:'Ecuador',timezone:'America/Guayaquil',longitude:-79.90},
  {city:'Lima',country:'Perú',timezone:'America/Lima',longitude:-77.04},
  {city:'Cusco',country:'Perú',timezone:'America/Lima',longitude:-71.97},
  {city:'La Paz',country:'Bolivia',timezone:'America/La_Paz',longitude:-68.15},
  {city:'Santiago',country:'Chile',timezone:'America/Santiago',longitude:-70.65},
  {city:'Buenos Aires',country:'Argentina',timezone:'America/Argentina/Buenos_Aires',longitude:-58.38},
  {city:'Córdoba',country:'Argentina',timezone:'America/Argentina/Cordoba',longitude:-64.18},
  {city:'Montevideo',country:'Uruguay',timezone:'America/Montevideo',longitude:-56.16},
  {city:'São Paulo',country:'Brasil',timezone:'America/Sao_Paulo',longitude:-46.63},
  {city:'Río de Janeiro',country:'Brasil',timezone:'America/Sao_Paulo',longitude:-43.17},
  {city:'Los Ángeles',country:'Estados Unidos',timezone:'America/Los_Angeles',longitude:-118.24},
  {city:'San Francisco',country:'Estados Unidos',timezone:'America/Los_Angeles',longitude:-122.42},
  {city:'Phoenix',country:'Estados Unidos',timezone:'America/Phoenix',longitude:-112.07},
  {city:'Houston',country:'Estados Unidos',timezone:'America/Chicago',longitude:-95.37},
  {city:'Chicago',country:'Estados Unidos',timezone:'America/Chicago',longitude:-87.63},
  {city:'Miami',country:'Estados Unidos',timezone:'America/New_York',longitude:-80.19},
  {city:'Nueva York',country:'Estados Unidos',timezone:'America/New_York',longitude:-74.01},
  {city:'Toronto',country:'Canadá',timezone:'America/Toronto',longitude:-79.38},
  {city:'Vancouver',country:'Canadá',timezone:'America/Vancouver',longitude:-123.12},
  {city:'Madrid',country:'España',timezone:'Europe/Madrid',longitude:-3.70},
  {city:'Barcelona',country:'España',timezone:'Europe/Madrid',longitude:2.17},
  {city:'Valencia',country:'España',timezone:'Europe/Madrid',longitude:-0.38},
  {city:'Sevilla',country:'España',timezone:'Europe/Madrid',longitude:-5.98},
  {city:'Lisboa',country:'Portugal',timezone:'Europe/Lisbon',longitude:-9.14},
  {city:'París',country:'Francia',timezone:'Europe/Paris',longitude:2.35},
  {city:'Londres',country:'Reino Unido',timezone:'Europe/London',longitude:-0.13},
  {city:'Roma',country:'Italia',timezone:'Europe/Rome',longitude:12.50},
  {city:'Berlín',country:'Alemania',timezone:'Europe/Berlin',longitude:13.40},
  {city:'Ámsterdam',country:'Países Bajos',timezone:'Europe/Amsterdam',longitude:4.90},
  {city:'Dubái',country:'E.A.U.',timezone:'Asia/Dubai',longitude:55.27},
  {city:'Nueva Delhi',country:'India',timezone:'Asia/Kolkata',longitude:77.21},
  {city:'Bangkok',country:'Tailandia',timezone:'Asia/Bangkok',longitude:100.50},
  {city:'Singapur',country:'Singapur',timezone:'Asia/Singapore',longitude:103.82},
  {city:'Hong Kong',country:'Hong Kong',timezone:'Asia/Hong_Kong',longitude:114.17},
  {city:'Pekín',country:'China',timezone:'Asia/Shanghai',longitude:116.41},
  {city:'Seúl',country:'Corea del Sur',timezone:'Asia/Seoul',longitude:126.98},
  {city:'Tokio',country:'Japón',timezone:'Asia/Tokyo',longitude:139.69},
  {city:'Sídney',country:'Australia',timezone:'Australia/Sydney',longitude:151.21},
  {city:'Auckland',country:'Nueva Zelanda',timezone:'Pacific/Auckland',longitude:174.76},
]

export function locationLabel(location:BirthLocation){return `${location.city}, ${location.country}`}

function normalize(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}

export function searchLocations(query:string,limit=8){
  const q=normalize(query.trim())
  if(!q)return []
  return locations.map(location=>{
    const city=normalize(location.city),country=normalize(location.country)
    const words=(value:string)=>value.split(' ').some(word=>word.startsWith(q))
    const score=city.startsWith(q)?0:words(city)?1:country.startsWith(q)?2:words(country)?3:-1
    return {location,score}
  }).filter(item=>item.score>=0).sort((a,b)=>a.score-b.score||a.location.city.length-b.location.city.length||a.location.city.localeCompare(b.location.city)).slice(0,limit).map(item=>item.location)
}
